"""지역 2(갈림길 숲) 몬스터 6종(16×16 프레임 2개).

몸통은 외곽선 없이 칠한 뒤 color_outline()으로 재질에 맞는 색 외곽선을 두른다(누리의 새 화풍).
빛은 왼쪽 위에서 온다. 각 몬스터는 문제 주제를 실루엣으로 읽히게 한다.
"""
import math

from forestpal import CH, color_outline, paint
from gridlib import overlay, shift

# ── 갈래 새싹: 줄기가 Y자로 두 갈래로 갈라진 새싹. 프레임 B는 잎을 들어 올리며 몸을 살짝 누른다 ────────
SPROUT_KEY = {"L": "f6", "M": "f5", "m": "f4", "g": "f3", "s": "f4", "S": "f2",
              "f": "w5", "d": "w4", "c": "w3", "b": "w2", "a": "w1", "e": "eye", "p": "blush", "r": "w2"}

_SPROUT_A = paint("""
    ................
    .LLM.......MLL..
    LMMmm.....mmMML.
    LMmmgs...sgmmML.
    .mggg.s.s.gggm..
    .......s........
    .......sS.......
    .....ddddcc.....
    ....dfdddddcb...
    ...dfdeddedcbb..
    ...dddeddeccbb..
    ...ddpddddpcbb..
    ...cdddeedccbb..
    ....ccccccccb...
    ...r..bbbbb..r..
    ................
""", SPROUT_KEY, 16, 16)

_SPROUT_B = paint("""
    LL.............L
    LMMm.........mML
    .Mmmgs.....sgmM.
    ..mgg.s...s.gg..
    .......s.s......
    ........s.......
    .......sS.......
    ................
    .....ddddcc.....
    ...ddfdddddcbb..
    ..ddfdeddedccbb.
    ..ddddeddeccbbb.
    ..dddpddddpccbb.
    ..ccdddeedcccbb.
    ...rcccccccccr..
    ................
""", SPROUT_KEY, 16, 16)

# ── 윤년 부엉이: 배에 달력 한 장(고리 철, 청록 머리띠, 날짜 칸, 빨갛게 표시한 29일). 프레임 B는 깡충 뛰며 날개를 편다 ──
OWL_KEY = {"a": "w1", "b": "w2", "c": "w3", "d": "w4", "D": "w5", "y": "a4", "Y": "a5", "e": "eye",
           "k": "a3", "W": "c3", "n": "c0", "R": "m2", "r": "m1", "f": "b3", "F": "b2", "s": "s4", "T": "i2"}

_OWL_A = paint("""
    ................
    ...b........b...
    ...cb......bc...
    ..cdDddddddddcb.
    ..cyyyYddyyyYcb.
    ..cyeyydcyeyycb.
    ..ccyyykkyyycbb.
    ..bcddddkdddcbb.
    ..bcdsddddsdcba.
    ..bcTsTTTTsTcba.
    ..bcWWWWWWWWcba.
    ..bbWnWnWnWWbba.
    ..abWnWnWRWWbaa.
    ..abWWWWWWWWbaa.
    ...abbbbbbbbaa..
    ....ff....ff....
""", OWL_KEY, 16, 16)

_OWL_B = paint("""
    ...b........b...
    ...cb......bc...
    ..cdDddddddddcb.
    ..cyyyYddyyyYcb.
    ..cyeyydcyeyycb.
    ..ccyyykkyyycbb.
    .bbcddddkdddcbba
    cbbcdsddddsdcbbb
    cb.cTsTTTTsTca.b
    c..bWWWWWWWWba.a
    ...bWnWnWnWWba..
    ...bWnWnWRWWba..
    ...bWWWWWWWWba..
    ...abbbbbbbbaa..
    ....Ff....Ff....
    ................
""", OWL_KEY, 16, 16)


# ── 고리 뱀: 제 꼬리를 문 보라 고리 뱀(우로보로스). 프레임 B는 비늘 띠가 돌아 고리가 도는 것처럼 보인다 ──
def _loop_snake(phase: int):
    ramp = ["v0", "v1", "v2", "v3", "v4"]
    g = [["."] * 16 for _ in range(16)]
    cx, cy = 7.5, 8.5
    r_out, r_in = 6.6, 3.1
    head_ang = -math.pi / 4  # 오른쪽 위
    for y in range(16):
        for x in range(16):
            dx, dy = x + 0.5 - cx - 0.5, y + 0.5 - cy - 0.5
            r = math.hypot(dx, dy)
            if not r_in <= r <= r_out:
                continue
            ang = math.atan2(dy, dx)
            # 머리 근처는 몸통을 비워 머리를 따로 그린다
            da = (ang - head_ang + math.pi) % (2 * math.pi) - math.pi
            if -0.35 < da < 0.45:
                continue
            # 고리 단면의 음영: 바깥쪽 위-왼쪽이 밝다
            nx, ny = dx / r, dy / r
            mid = (r_in + r_out) / 2
            t = (r - mid) / ((r_out - r_in) / 2)  # -1(안) ~ 1(밖)
            light = -(nx * 0.6 + ny * 0.8) * t + (1 - abs(t)) * 0.8
            k = 1 + round(max(-1, min(1.6, light)) * 1.4)
            k = max(0, min(4, k))
            ch = ramp[k]
            # 배 쪽(안쪽 가장자리)은 노란 배 비늘
            if t < -0.45:
                ch = "a3" if light > 0 else "a2"
            # 비늘 띠(각도 방향으로 반복, phase에 따라 회전)
            band = int(((ang + math.pi) / (2 * math.pi) * 10 + phase * 0.5)) % 2
            if band and -0.2 < t < 0.75 and ch in ("v2", "v3"):
                ch = "v1" if ch == "v2" else "v2"
            g[y][x] = CH[ch]
    # 머리: 오른쪽 위에서 고리 쪽(왼쪽 아래)을 보며 꼬리 끝을 물고 있다
    head = paint("""
        ........HHHH....
        .......HhhhhH...
        ......HhYEhhhH..
        ......HhEEhhhH..
        .....mmmmhhhvH..
        .....RttmhvvH...
        ......mmvvvH....
        ........vv......
    """, {"H": "v2", "h": "v4", "Y": "white", "E": "eye", "m": "v0", "R": "m2", "t": "a4", "v": "v3"}, 16, 8)
    if phase:
        head = overlay(head, paint("""
            ................
            ................
            ........EE......
            ................
            ................
            ................
            ................
            ................
        """, {"E": "v4"}, 16, 8))
    rows = ["".join(r) for r in g]
    rows = overlay(rows, head, 0, 0)
    return rows


# ── 세는 버섯: 갓의 점이 숫자. 프레임 A는 3·2·1, 프레임 B는 한 칸씩 줄어 2·1·0(거꾸로 센다) ──────────
SHROOM_KEY = {"a": "m0", "b": "m1", "c": "m2", "d": "m3", "D": "m4", "W": "c3", "w": "c2",
              "s": "c2", "S": "c3", "t": "c1", "T": "c0", "e": "eye", "p": "blush"}

_DIGITS = {
    "0": ["WWW", "W.W", "W.W", "W.W", "WWW"],
    "1": [".W.", "WW.", ".W.", ".W.", "WWW"],
    "2": ["WW.", "..W", ".W.", "W..", "WWW"],
    "3": ["WW.", "..W", ".W.", "..W", "WW."],
}

_SHROOM_BODY = """
    ................
    .....bccccb.....
    ...bcdDdddccb...
    ..bcdDddddcccb..
    .bcddddddccccba.
    .bcddddddccccba.
    bcdddddddcccccba
    bccddddcccccccba
    abbbbbbbbbbbbbaa
    ...TtSSSSStT....
    ...tSSeSSeSt....
    ...tSpSSSSpt....
    ...TtSSeeStT....
    ...TttttttT.....
    ..bb.......bb...
    ................
"""


def _count_shroom(digits: str, squash: bool):
    body = paint(_SHROOM_BODY, SHROOM_KEY, 16, 16)
    # 숫자 점: 갓 위 세 자리(왼쪽 위로 기울어진 갓에 맞춰 가운데가 한 칸 위)
    spots = [(2, 3), (6, 2), (10, 3)]
    for d, (sx, sy) in zip(digits, spots):
        glyph = paint("\n".join(_DIGITS[d]), {"W": "c3"}, 3, 5)
        body = overlay(body, glyph, sx, sy)
    if squash:
        # 줄기를 한 칸 줄이고 갓을 한 칸 내려 눌린 모습
        top = body[:9]
        stem = body[9:13]
        bottom = body[13:]
        body = ["." * 16] + top + stem[:1] + stem[2:] + bottom
        body = body[:16]
    return color_outline(body)


# ── 우박 도깨비불: 얼음빛 불꽃에 얼굴, 둘레를 도는 우박 세 알. 프레임 B는 불꽃 끝이 흔들리고 우박이 돈다 ─
WISP_KEY = {"0": "i0", "1": "i1", "2": "i2", "3": "i3", "4": "i4", "5": "i5", "w": "white", "e": "eye", "p": "blush"}

_WISP_A = paint("""
    .......3........
    ......34........
    .....345..3.....
    .....3452.4.....
    ....2345534.....
    ...234555542....
    ...2345555432...
    ..234e555e432...
    ..234e555e432...
    ..2345p5p5432...
    ..2234555432....
    ...22344432.....
    ....222322......
    .....2..2.......
    ................
    ................
""", WISP_KEY, 16, 16)

_WISP_B = paint("""
    ................
    ..........3.....
    .....3....43....
    .....43..343....
    .....4433542....
    ...234555542....
    ...2345555432...
    ..234e555e432...
    ..234e555e432...
    ..2345p5p5432...
    ...234555432....
    ...22344432.....
    ....222322......
    ......2..2......
    ................
    ................
""", WISP_KEY, 16, 16)

_HAIL = {"w": "white", "4": "i4", "3": "i3"}
_HAIL_A = [(0, 4), (13, 2), (12, 12)]
_HAIL_B = [(1, 11), (12, 5), (5, 13)]


def _wisp(body, hail):
    g = color_outline(body)
    stone = color_outline(paint("""
        ....
        .w4.
        .43.
        ....
    """, _HAIL, 4, 4))
    for x, y in hail:
        g = overlay(g, stone, x - 1, y - 1)
    return g


# ── 도토리 진드기: 도토리 몸통에 다리 여섯, 깍정이 모자. 프레임 B는 다리가 번갈아 움직인다 ───────────────
ACORN_KEY = {"a": "w0", "b": "w1", "c": "w2", "d": "w3", "e": "w4", "f": "w5",
             "n": "a1", "N": "a2", "o": "a3", "O": "a4", "Y": "a5", "E": "eye", "W": "white", "s": "b2"}

_ACORN_BODY = """
    ................
    .......cb.......
    .......dc.......
    ....edededdc....
    ...eddeddeddc...
    ..ededdeddeddc..
    ..dcdcdcdcdcdb..
    ...ONNNNNNNNn...
    ...OoWEoWEoNn...
    ...OoooooonNn...
    ...oONooooNNn...
    ....oNNNNNNn....
    .....nNNNNn.....
    ......nnnn......
    ................
    ................
"""

_ACORN_LEGS_A = """
    ................
    .....b....b.....
    ......b..b......
    ................
    ................
    ................
    ................
    ..............B.
    BBb..........bBB
    B..............B
    .bbb........bbb.
    b..............b
    ...Bb......bB...
    ..B..........B..
    ................
    ................
"""

_ACORN_LEGS_B = """
    ................
    ....b......b....
    .....b....b.....
    ................
    ................
    ................
    ................
    ................
    .Bbb........bbB.
    B..............B
    ..bbb......bbb..
    .B............B.
    .B..bB....Bb..B.
    ......B..B......
    ................
    ................
"""


def _acorn(legs_text, bob):
    legs = paint(legs_text, {"b": "w3", "B": "w2"}, 16, 16)
    body = paint(_ACORN_BODY, ACORN_KEY, 16, 16)
    if bob:
        body = shift(body, 0, 1)
    return color_outline(overlay(legs, body))


FOREST_MONSTERS = {
    "monster_fork_sprout": [color_outline(_SPROUT_A), color_outline(_SPROUT_B)],
    "monster_leap_owl": [color_outline(_OWL_A), color_outline(_OWL_B)],
    "monster_loop_snake": [color_outline(_loop_snake(0)), color_outline(_loop_snake(1))],
    "monster_count_shroom": [_count_shroom("321", False), _count_shroom("210", True)],
    "monster_hail_wisp": [_wisp(_WISP_A, _HAIL_A), _wisp(_WISP_B, _HAIL_B)],
    "monster_acorn_mite": [_acorn(_ACORN_LEGS_A, False), _acorn(_ACORN_LEGS_B, True)],
}
