"""지역 2 NPC 걷기 시트(16×16 × 8프레임: 아래×2, 왼쪽×2, 오른쪽×2, 위×2).

characters.py의 character()로 다리를 끼워 8프레임을 만들고, 외곽선 K는 닿은 재질의 색 외곽선으로 바꾼다
(누리와 같은 새 화풍).

- npc_traveler: 같은 자리를 맴도는 여행자. 챙 넓은 모자(청록 띠), 청록 목도리, 먼지 낀 청회색 망토,
  손에 든 지도, 등에 침낭을 얹은 배낭.
- npc_woodcutter: 나무꾼. 방울 달린 빨간 털모자, 덥수룩한 갈색 수염, 빨간 체크 셔츠, 어깨에 멘 도끼.
"""
from characters import character
from forestpal import CH, color_outline, paint

TRAVELER_KEY = {"d": "w3", "e": "w4", "c": "w2", "t": "i3", "h": "h2", "H": "h1", "s": "k3", "S": "k2",
                "o": "eye", "p": "blush", "T": "i3", "U": "i4", "q": "q2", "Q": "q3", "n": "q1",
                "m": "c3", "M": "c1", "b": "w2", "B": "w3", "r": "c2", "R": "c1"}

TRAVELER_DOWN = paint("""
    ......KKKK......
    .....KdeedK.....
    ....KddeddcK....
    ....KttttttK....
    ..KKeedddddccKK.
    .KeeddddddddcccK
    ..KKhhhhhhhhKK..
    ...KhsssssshK...
    ...KsossssosK...
    ...KpsssssspK...
    ..KTUUTTTTTTTK..
    .KqQQqqTTqqqqnK.
    .KsKqmmMmmqqKsK.
    ..KKnqmmMmqnKK..
""", TRAVELER_KEY, 16, 14)

TRAVELER_RIGHT = paint("""
    .....KKKK.......
    ....KdeedK......
    ...KddeddcK.....
    ...KttttttK.....
    .KKeeddddddcKK..
    KeedddddddddcccK
    ..KrhhhssssK....
    .KRrhhsssosK....
    .KBbhhssssSK....
    .KBbhhSsspK.....
    .KBbqqqTTUK.....
    .KBbqqQqTTK.....
    .KBbqQQqsmK.....
    ..KKnqqqqK......
""", TRAVELER_KEY, 16, 14)

TRAVELER_UP = paint("""
    ......KKKK......
    .....KdeedK.....
    ....KddeddcK....
    ....KttttttK....
    ..KKeedddddccKK.
    .KeeddddddddcccK
    ..KKhhhhhhhhKK..
    ...KhHhhhhHhK...
    ..KRrrrrrrrrRK..
    ..KBBBBBBBBbbK..
    .KqBbbbbbbbbbqK.
    .KqBbBBBBBbbbqK.
    .KsKbbbbbbbbKsK.
    ..KKnqqqqqqnKK..
""", TRAVELER_KEY, 16, 14)

WOOD_KEY = {"R": "r3", "r": "r2", "a": "r1", "x": "r0", "w": "c3", "h": "h2", "H": "h3", "b": "h1",
            "s": "k3", "S": "k2", "o": "eye", "p": "blush", "A": "s4", "Z": "s5", "z": "s2", "l": "w3", "L": "w4"}

WOODCUTTER_DOWN = paint("""
    ......KwwK...KK.
    .....KrRRrK.KAZK
    ....KrRrrrrKzAAK
    ...KrRrrrrrrKKlK
    ..KaaaaaaaaaaKlK
    ..KhssssssssKlK.
    ..KhsossssosKlK.
    ..KhHssSSssHKlK.
    ..KHHHsppsHHHKK.
    ...KHHhhhhHHK...
    ..KrKxHhhHxKrK..
    .KrRrxrHHrxRrrK.
    .KsKrxrrrrxrKsK.
    ..KKaxaaaaxaKK..
""", WOOD_KEY, 16, 14)

WOODCUTTER_RIGHT = paint("""
    ......KwwK......
    .....KrRRrK.....
    ....KrRrrrrK....
    ...KrRrrrrrrK...
    ...KaaaaaaaaaK..
    ...KhhhsssoK....
    ...KhhhssssK....
    ...KhhhHHsSK....
    ...KhhhHHHHHK...
    ....KKhHHHHK....
    .KKKKrrxHHK.....
    KZAAzLLLLLLLK...
    KzAKKrrxrsK.....
    .KK.KaaxaaK.....
""", WOOD_KEY, 16, 14)

WOODCUTTER_UP = paint("""
    ......KwwK......
    .....KrRRrK.....
    ....KrRrrrrK....
    ...KrRrrrrrrK...
    ..KaaaaaaaaaaK..
    ..KhhhhhhhhhhK..
    ..KhhhhhhhhhhK..
    ...KhhhhhhhhK.K.
    ...KKhhhhhhKKlK.
    .KK.KKKKKKKKlK..
    KAZKrrxrrxKlrK..
    KzAAlLlrrxlrRK..
    .KKKsKxrrxrrKsK.
    ...KKaxaaxaaKK..
""", WOOD_KEY, 16, 14)


def _sheet(down, right, up, pants, boots):
    return [color_outline(f) for f in character(down, right, up, CH[pants], CH[boots])]


FOREST_CHARACTERS = {
    "npc_traveler": _sheet(TRAVELER_DOWN, TRAVELER_RIGHT, TRAVELER_UP, "w2", "w0"),
    "npc_woodcutter": _sheet(WOODCUTTER_DOWN, WOODCUTTER_RIGHT, WOODCUTTER_UP, "q1", "w1"),
}
