"""몬스터·오브젝트(16×16 프레임 2개)와 보스(32×32 프레임 2개).

몸통은 외곽선 없이 칠한 뒤 outline()으로 1px 짙은 외곽선을 두른다(문자 'K').
"""
from gridlib import grid, outline, overlay

# ── 타입 슬라임: 'str' 꼬리표를 단 젤리. 프레임 B는 납작하게 눌린 모습 ─────────────
_SLIME_A = grid("""
    ................
    ................
    ...........b....
    ..........bWWWW.
    .........b.WgWg.
    ......EEEE.WWWW.
    ....EElllEEE....
    ...EllEEEEEEe...
    ...ElEEEEEEEe...
    ..EEEKEEEEKEEe..
    ..EEEKEEEEKEee..
    ..EEEEEKKEEEee..
    ..eEEEEEEEEEee..
    ..eeEEEEEEEeee..
    ...eeeeeeeeee...
    ................
""", 16, 16)

_SLIME_B = grid("""
    ................
    ................
    ................
    ................
    ............b...
    ...........bWWWW
    ..........b.WgWg
    .....EEEEEE.WWWW
    ...EEllllEEEE...
    ..EllEEEEEEEEe..
    .EEEEKEEEEKEEee.
    .EEEEKEEEEKEEee.
    .eEEEEEKKEEEEee.
    .eeEEEEEEEEEeee.
    ..eeeeeeeeeeee..
    ................
""", 16, 16)

# ── 나머지 박쥐: 나눗셈의 '나머지' 금화 한 닢을 움켜쥔 보라 박쥐. 날개 위/아래 ───────
_BAT_A = grid("""
    ................
    .p............p.
    .pp..........pp.
    .pPp.p....p.pPp.
    .pPPppp..pppPPp.
    .pPPPpPPPPpPPPp.
    .pPPpPYPPYPpPPp.
    .pPp.pPPPPp.pPp.
    .pp..pPWWPp..pp.
    .p....pppp....p.
    .......UU.......
    ......UYYU......
    ......UUUu......
    .......uu.......
    ................
    ................
""", 16, 16)

_BAT_B = grid("""
    ................
    ................
    ................
    .....p....p.....
    .....ppppppp....
    .....pPPPPp.....
    ..ppppYPPYpppp..
    .pPPpPPPPPPpPPp.
    pPPPPpPWWPpPPPPp
    pPPpppppppppPPPp
    pPp...pUUp...pPp
    pp....UYYU....pp
    p.....UUUu.....p
    .......uu.......
    ................
    ................
""", 16, 16)

# ── 철갑 두더지: 리벳 박힌 철 투구, 흙더미에서 솟아오름 ─────────────────────────
_MOLE_A = grid("""
    ................
    ................
    ................
    .....HHHHHH.....
    ....HWHHHHHG....
    ...HWHHGHHHGg...
    ...GGGGGGGGgg...
    ...bBKBBBBKBb...
    ...BBBBiiBBBB...
    ..H.BBBiiBBB.H..
    .HWH.BBBBBB.HGH.
    .HGHBBBBBBBBHGH.
    ..nnnnnnnnnnnnn.
    .nNNnnnnnnnNnnnn
    nnnnnBnnnnnnBnnn
    ................
""", 16, 16)

_MOLE_B = grid("""
    ................
    ................
    ................
    ................
    .....HHHHHH.....
    ....HWHHHHHG....
    ...HWHHGHHHGg...
    ...GGGGGGGGgg...
    ...bBKBBBBKBb...
    .H.BBBBiiBBBB.H.
    HWHBBBBiiBBBBHGH
    HGH.BBBBBBBB.HGH
    ..nnnnnnnnnnnnn.
    .nNNnnnnnnnNnnnn
    nnnnnBnnnnnnBnnn
    ................
""", 16, 16)

# ── 메아리 유령: 반투명 하늘빛, 동그랗게 벌린 입에서 메아리 고리가 퍼진다 ─────────────
_GHOST_A = grid("""
    ................
    ................
    .....cccc.......
    ...cc1111cc.....
    ..c11111111c....
    ..c1K11K111c....
    .c11K11K1111c...
    .c1111111111c...
    .c111KK11111c...
    .c11K11K1111c...
    .c111KK11111c...
    .c1111111111c...
    .c11111111111c..
    .c1111c111c11c..
    ..c11c.c1c.cc...
    ...cc...c.......
""", 16, 16)

_GHOST_B = grid("""
    ................
    ................
    ................
    .....cccc.......
    ...cc1111cc.....
    ..c11111111c....
    ..c1K11K111c....
    .c11K11K1111c...
    .c11111111111c..
    .c111KK11111c...
    .c11K11K1111c...
    .c111KK11111c...
    .c1111111111c...
    .c111c111c11c...
    .c11c.c1c.c1c...
    ..cc...c...c....
""", 16, 16)

# ── 구분자 요정: '-' 막대를 두 손으로 든 작은 요정. 날개 파닥임 ───────────────────
_SEP_A = grid("""
    ................
    ................
    ..33.......33...
    .3cc3.YYY.3cc3..
    .3cc3YYYYY3cc3..
    ..3c3YsssY3c3...
    ..3cc3KsK3cc3...
    ...33sssss33....
    ....3iiiii3.....
    .WWWWWiiiiWWWWW.
    ....iiiiiii.....
    ....iiiiiii.....
    .....s...s......
    ................
    ................
    ................
""", 16, 16)

_SEP_B = grid("""
    ................
    ................
    ................
    ......YYY.......
    .....YYYYY......
    .....YsssY......
    ..33.3KsK3.33...
    .3cc3sssss3cc3..
    .3ccc3iii3ccc3..
    .WWWWWiiiiWWWWW.
    ..333.iiiii333..
    ....iiiiiii.....
    .....s...s......
    ................
    ................
    ................
""", 16, 16)

# ── 시계 딱정벌레: 등껍질이 시계 문자판. 프레임마다 바늘과 다리가 움직인다 ──────────
_BEETLE_A = grid("""
    ................
    .....g....g.....
    ......g..g......
    ......gggg......
    .....gYggYg.....
    .g...UUUUUU...g.
    ..g.UWWKWWWu.g..
    ...UWWWKWWWWu...
    .ggUKWWKWWWKuggg
    ...UWWWKKKWWu...
    ...UWWWWWWWWu...
    ..guWWWWWWWWug..
    .g.uWWWWKWWWu.g.
    ....uWWWWWWu....
    .....uuuuuu.....
    ................
""", 16, 16)

_BEETLE_B = grid("""
    ................
    ....g......g....
    .....g....g.....
    ......gggg......
    .....gYggYg.....
    ..g..UUUUUU..g..
    .g..UWWWWWWu..g.
    ...UWWWWWWWWu...
    ggguKWWKWWWKuggg
    ...UWWWKWWWWu...
    ...UWWWKWWWWu...
    .g.uWWWKWWWWu.g.
    ..guWWWWKWWWug..
    ....uWWWWWWu....
    .....uuuuuu.....
    ................
""", 16, 16)

# ── 오브젝트 ──────────────────────────────────────────────────────────────────
_CHEST_CLOSED = grid("""
    ................
    ................
    ................
    ................
    ..BBBBBBBBBBBB..
    .BnnnnnnnnnnnnB.
    .BnUnnnnnnnnUnB.
    .BBUBBBBBBBBUBB.
    .UUUUUUYYUUUUUU.
    .BnUnnnUunnnUnB.
    .BnUnnnUunnnUnB.
    .BnUnnnnnnnnUnB.
    .BbUbbbbbbbbUbB.
    .BBBBBBBBBBBBBB.
    ................
    ................
""", 16, 16)

_CHEST_OPEN = grid("""
    ................
    ..BBBBBBBBBBBB..
    .BbbbbbbbbbbbbB.
    .BbUbbbbbbbbUbB.
    .BnUnnnnnnnnUnB.
    .BbbbbbbbbbbbbB.
    .BkkYkYYkkYkkkB.
    .BYUYYUYYUYYUYB.
    .UUUUUUUUUUUUUU.
    .BnUnnnnnnnnUnB.
    .BnUnnnnnnnnUnB.
    .BnUnnnnnnnnUnB.
    .BbUbbbbbbbbUbB.
    .BBBBBBBBBBBBBB.
    ................
    ................
""", 16, 16)

_SIGN = grid("""
    ................
    ................
    ................
    .nnnnnnnnnnnnnn.
    .nNNNNNNNNNNNNn.
    .nNbbbNbbNbbNBn.
    .nNNNNNNNNNNNBn.
    .nNbbNbbbbNNNBn.
    .nNNNNNNNNNNNBn.
    .nBBBBBBBBBBBBn.
    .nnnnnnBBnnnnnn.
    ......nBBn......
    ......nBBn......
    ......nBBn......
    .....eenBnee....
    ................
""", 16, 16)

_SIGN_B = _SIGN

_FIRE_A = grid("""
    ................
    ................
    ................
    .......x........
    ......xx...x....
    ......xRx..x....
    .....xRRxxxR....
    ....xRRyRxRRx...
    ....xRyYyRRyx...
    ....xRyYYyRyx...
    .....xRYYYyx....
    ...BnnRyyRnnBB..
    ..BnnbBnnBbnnB..
    ..BBnnbBBbnnBB..
    ...GGGGGGGGGG...
    ................
""", 16, 16)

_FIRE_B = grid("""
    ................
    ................
    ................
    .........x......
    ....x...xx......
    ....xx..xRx.....
    ....xRxxRRx.....
    ...xRRxRRyRx....
    ...xyRRyYyRx....
    ....xRyYYyRx....
    .....xyYYyx.....
    ...BnnRyyRnnBB..
    ..BnnbBnnBbnnB..
    ..BBnnbBBbnnBB..
    ...GGGGGGGGGG...
    ................
""", 16, 16)

# 비석: 서펜트 룬(뱀 모양 S)이 청록으로 빛난다. 프레임 B는 더 밝고 반짝임이 떠오른다.
_RUNE_A = grid("""
    ................
    ................
    ......GGGG......
    .....GHHHHG.....
    ....GHHHHHgG....
    ....GHTTTHgG....
    ....GHTHHHgG....
    ....GHTTTHgG....
    ....GHHHTHgG....
    ....GHTTTHgG....
    ....GHHHHHgG....
    ....GHHHHggG....
    ...gGGGGGGGGg...
    ..egggggggggge..
    ................
    ................
""", 16, 16)

_RUNE_B = grid("""
    ................
    ................
    ......GGGG......
    .....GHHHHG.....
    ....GHcccHgG....
    ....GHcTTcgG....
    ....GHcHHHgG....
    ....GHccccgG....
    ....GHHHHcgG....
    ....GHcccTgG....
    ....GHHHHHgG....
    ....GHHHHggG....
    ...gGGGGGGGGg...
    ..egggggggggge..
    ................
    ................
""", 16, 16)

# 문: 돌 문틀의 나무 문. [닫힘, 열림] — 열리면 가운데가 비어 뒤의 바닥이 보인다.
_DOOR_CLOSED = grid("""
    ....GGGGGGGG....
    ..GGHHHHHHHHGG..
    .GHHGGGGGGGGHHg.
    .GHGbBBBBBBbGHg.
    .GHbBnBBnBBBbHg.
    .GHbBnBBnBBBbHg.
    .GHbBnBBnBBBbHg.
    .GHbBnBBnBBBbHg.
    .GHbBnBBnBUYbHg.
    .GHbBnBBnBUubHg.
    .GHbBnBBnBBBbHg.
    .GHbBnBBnBBBbHg.
    .GHbBnBBnBBBbHg.
    .GHbBnBBnBBBbHg.
    .GHbbbbbbbbbbHg.
    .ggg........ggg.
""", 16, 16)

_DOOR_OPEN = grid("""
    ....GGGGGGGG....
    ..GGHHHHHHHHGG..
    .GHHGGGGGGGGHHg.
    .GHGb.......GHg.
    .GHbn.......bHg.
    .GHbn........Hg.
    .GHbn........Hg.
    .GHbn........Hg.
    .GHbU........Hg.
    .GHbn........Hg.
    .GHbn........Hg.
    .GHbn........Hg.
    .GHbn........Hg.
    .GHbn........Hg.
    .GHbb........Hg.
    .ggg........ggg.
""", 16, 16)


def _o(g, extra=None):
    """외곽선을 두르고, extra(외곽선 없이 덧그릴 빛·고리 등)를 위에 얹는다."""
    g = outline(g)
    return overlay(g, extra) if extra else g


# 메아리 고리(외곽선 없음)
_ECHO_A = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ..............T.
    ...............T
    ...............T
    ..............T.
    ................
    ................
    ................
    ................
    ................
""", 16, 16)

_ECHO_B = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ..............c.
    ...............c
    ...............c
    ..............c.
    ................
    ................
    ................
    ................
""", 16, 16)

_RUNE_GLINT = grid("""
    ................
    .c..............
    .............c..
    ................
    ................
    ..c.............
    ................
    .............c..
    ................
    ...c............
    ................
    ................
    ................
    ................
    ................
    ................
""", 16, 16)


MONSTERS = {
    "monster_type_slime": [_o(_SLIME_A), _o(_SLIME_B)],
    "monster_remainder_bat": [_o(_BAT_A), _o(_BAT_B)],
    "monster_iron_mole": [_o(_MOLE_A), _o(_MOLE_B)],
    "monster_echo_ghost": [_o(_GHOST_A, _ECHO_A), _o(_GHOST_B, _ECHO_B)],
    "monster_sep_sprite": [_o(_SEP_A), _o(_SEP_B)],
    "monster_clock_beetle": [_o(_BEETLE_A), _o(_BEETLE_B)],
}

OBJECTS = {
    "obj_chest": [_o(_CHEST_CLOSED), _o(_CHEST_OPEN)],
    "obj_sign": [_o(_SIGN), _o(_SIGN_B)],
    "obj_campfire": [_o(_FIRE_A), _o(_FIRE_B)],
    "obj_rune": [_o(_RUNE_A), _o(_RUNE_B, _RUNE_GLINT)],
    "obj_door": [_o(_DOOR_CLOSED), _o(_DOOR_OPEN)],
}
