"""마을 시설 오브젝트(단위 3-1, docs/phase3/plan.md §5.2): 그림자 게시판(obj_board), 상점 가판대(obj_shop).

16×16 프레임 2개. 몸통은 외곽선 없이 칠하고 outline()으로 외곽선을 두른다.
"""
from gridlib import grid, outline, overlay

# 그림자 게시판: 나무 판에 그림자 수배지(보라)와 퀘스트 쪽지(흰색). 프레임 B는 수배지의 눈이 빛난다
_BOARD = grid("""
    ................
    .bbbbbbbbbbbbbb.
    .bnnnnnnnnnnnnb.
    .bnppppnWWWWnnb.
    .bnpkkpnWmmWnnb.
    .bnpkkpnWWWWnnb.
    .bnppppnnnnnnnb.
    .bnnnnnnWWWnppb.
    .bnmmmnnWmWnpkb.
    .bnnnnnnWWWnppb.
    .bbbbbbbbbbbbbb.
    ...bB......bB...
    ...bB......bB...
    ...bB......bB...
    ..eebBe...ebBee.
    ................
""", 16, 16)

_BOARD_GLINT = grid("""
    ................
    ................
    ................
    ................
    ....PP..........
    ................
    ..............P.
    ................
    .............P..
    ................
    ................
    ................
    ................
    ................
    ................
    ................
""", 16, 16)

# 상점 가판대: 빨강·흰 줄무늬 차양, 나무 매대 위 물약과 금화. 프레임 B는 금화가 반짝인다
_SHOP = grid("""
    ................
    ..xxWWxxWWxxWW..
    .xxWWxxWWxxWWxx.
    .XxWXxWXxWXxWXX.
    ..b..........b..
    ..b..........b..
    ..b..UY..TT..b..
    ..b..uU.xTTx.b..
    .nnnnnnnnnnnnnn.
    .NNNNNNNNNNNNNN.
    .nBBBBBBBBBBBBn.
    .nB..........Bn.
    .nBnnnnnnnnnnBn.
    .nB..........Bn.
    .nnnnnnnnnnnnnn.
    ................
""", 16, 16)

_SHOP_GLINT = grid("""
    ................
    ................
    ................
    ................
    ................
    ......W.........
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
""", 16, 16)


def _o(g, extra=None):
    g = outline(g)
    return overlay(g, extra) if extra else g


TOWN_OBJECTS = {
    "obj_board": [_o(_BOARD), _o(_BOARD, _BOARD_GLINT)],
    "obj_shop": [_o(_SHOP), _o(_SHOP, _SHOP_GLINT)],
}
